version: '3.8'
services:
  user-srv:

    build: .
#      context: .
#      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - $PWD:/userapp
    links:
      - db
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - $PWD/docker_config
    ports:
      - "33061:3306"
    volumes:
      - $PWD/.db:/var/lib/mysql
