version: '3.8'
services:
  user-srv:
    build:
     context: user_app
     dockerfile: users.Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - $PWD/user_app:/userapp
    links:
      - db
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - $PWD/docker_config
    ports:
      - "33061:3306"
    volumes:
      - $PWD/user_app/.db:/var/lib/mysql
